### ISSUE TITLE
support deployment config migration

### ISSUE THREAD

**Issue by marc-portier** [vlizBE/vocabserver-app#33]
would be nice if the essential settings of a service could be exported and moved to another server

this would include:
- list of vocabs, for each vocab:
  - name
  - alias (if any) --> see issue #32
  - optionally its uuid
  - the associated sources, for each source:
    -  type (dump or ldes)
    - url
    - additionals: deref needed, max num requests, prefered content-type
  - the associated mapping to use in unification

during import
- a sensible usage can be assumed
- only essential system protection measurements should be taken into account
- the uuid could be used to detect duplication (to be decided id new uuid should be assigned, or the entry skipped, or the existing one updated)
- even more of the steps in the flow could be triggered automatically (all the way up to started unification / ingest ?) 

use cases:
- move the config tested in a dev environment to production
- save and reinstall config over an upgrade that cleared all data

**Comment by nvdk** [comment]
addressed in the 1.1 release
