### ISSUE TITLE
can't delete vocabulary

### ISSUE THREAD

**Issue by marc-portier** [vlizBE/vocabserver-app#35]
trying to remove a vocab only yields a 500 error --> only visible in the console
the vocab that was attempted to be deleted is still in the list after refresh

**Comment by nvdk** [comment]
couldn't reproduce (got a `200 OK`), but in any case we need to improve error handling here.

**Comment by marc-portier** [comment]
answer: LDES.
however: since I was able to succesfully test a create-delete cycle for an LDES vocab on another server -- will simply redeploy that first server and assume it will just work

remaining issue is rather one of UI feedback - maybe to be handled inside 1.1 via #31 ?

will add a suggestion over there.

think we can close this one for now
