### ISSUE TITLE
sorting of vocabs is broken

### ISSUE THREAD

**Issue by marc-portier** [vlizBE/vocabserver-app#36]
### entering without sort at `/vocabularies`
![image](https://github.com/vlizBE/vocabserver-app/assets/299574/2b2fdab6-31c2-475b-9f4e-96c6030c1081)
remark: 
* as fresh entry the user should not be expecting any ordering, but since the UI is claiming it in the title `[asc]name` things should be sorted accordingly, they are not
* MI-Persons should be last in list, not above the broken** entries (after the shared capital M, the capital i should be after lowercase a)
* P06 should be 3rd - i.e. behind P01 

### clicking once on the title leads to `/vocabularies?sort=-name`
![image](https://github.com/vlizBE/vocabserver-app/assets/299574/a7bb175c-ee98-4674-acff-14fd7eccc180)
remark:
* as a user I pleasantly experience some reaction to my wish
* still dead wrong sorting result though

### clicking again leads to `/vocabularies?sort=`
![image](https://github.com/vlizBE/vocabserver-app/assets/299574/fa938811-a0a3-41b7-9c8d-cbd2b6ac0472)

remark:
* apparently the click on the column head works as a 3-state toggle -- now sorting has been removed, so ok I guess but slightly surprising -- a separate click-zone (x) to remove sorting would probably be less surprising
* indeed another click brings us back at `/vocabularies`

### manually hacking the url to some wild guess `/vocabularies?sort=name`
![image](https://github.com/vlizBE/vocabserver-app/assets/299574/e3ccb887-b149-41e9-9df2-b26939f54855)

remark: 
* nice that this works too as an alias for the default entry `/vocabularies`
* however, the actual sorting wrong as mentioned on top

**Comment by nvdk** [comment]
fixed in the 1.1 release
