### ISSUE TITLE
no user-feedback when submitting "mapping" config

### ISSUE THREAD

**Issue by marc-portier** [vlizBE/vocabserver-app#50]
when a new mapping config is submitted (blue submit button at the bottom of the form) 
the end user is not getting any feedback off that fact -- leaving them wondered: did I push?

**Comment by marc-portier** [comment]
slightly changing the state icon from "question-mark" (unkown / todo) to "checked" (done / completed)  would be the easiest?

**Comment by nvdk** [comment]
should be fixed in 1.1 release
