### ISSUE TITLE
Convert services to images

### ISSUE THREAD

**Issue by MilanLamote** [vlizBE/vocabserver-app#55]
Images are already being created but using them as the services image does not work.
The app does not function properly:

- can't download file dump
- does no indexing

At first glance the contents of these images seem correct. We do wonder about the line. This should be covered in the Dockerfile during build?
`volumes:
      - ./services/vocab-configs/:/app`
Needs further debugging.

**Comment by MikiDi** [comment]
Closed by https://github.com/vlizBE/vocabserver-app/pull/56/files
