### ISSUE TITLE
migration export for LDES services does not include the feed-url

### ISSUE THREAD

**Issue by marc-portier** [vlizBE/vocabserver-app#57]
When doing an export - remove - import cycle on a vocabulary that uses an LDES source, the "source" appears to be empty / nonexistent after import.

Investigation learns that the feed-address is not part of the exported config file.

Tested on 
 
![image](https://github.com/vlizBE/vocabserver-app/assets/299574/00a77e4b-4bc5-426f-8e73-910ce255077f)

Yielding the export-file shared at https://github.com/vlizBE/vocabserver-deploy/blob/main/vocab-config/marine-regions-gazetteer.vocab-config.ttl

which has no mention of the feed url: "https://marineregions.org/feed"  ?

**Comment by x-m-el** [comment]
Zie https://github.com/vlizBE/vocabserver-app/pull/58 voor de fix.
