### ISSUE TITLE
LDES harvesting fails on all different feeds for VLIZ build

### ISSUE THREAD

**Issue by cedricdcc** [vlizBE/vocabserver-app#64]
No LDES feed is being harvested by the vocabserver-app.

The feeds that were tested for this were:
 - [marineregions](https://marineregions.org/feed)
 - [BODC-P02](http://vocab.nerc.ac.uk/ldes/P02/)

All of the above for the build that redpencil has but also the build-images locally from the vocabserver-app as the ghcr.io images do not complete this task succesfully.

Current investigation of the logs from the docker-stack point to a [mint transport error](https://hexdocs.pm/mint/Mint.TransportError.html) coming from the semtech/mu-identifier image

**Comment by MikiDi** [comment]
The `Mint transport error`s are thrown in `identifier` and `dispatcher` on completion of each request to `mu-cl-resources`, which by default is configured to do HTTP connection reuse. The error comes up each time a TCP connection is closed without further consequences.

**Comment by MikiDi** [comment]
During today's meeting we found that -for some still to-be-determinded reason- the `ldes-consumer-manager` didn't function properly on the Windows machine Cedric tested with. Each time the Python docker library [tries to pull the ldes consumer image](https://github.com/redpencilio/ldes-consumer-manager/blob/57104366ed8365c1750b1f472fc9fc7b7c4ea96d/web.py#L31) the WSGI worker crashes and another one is respawned. Running the service in development mode fixes the problem for now.
