### ISSUE TITLE
Loading LDES Configuration File won't start Docker Container for harvesting LDES feed

### ISSUE THREAD

**Issue by cedricdcc** [vlizBE/vocabserver-app#65]
I am experiencing a problem with the vocabserver-app project involving the loading of a  configuration file with a LDES source specified. A configuration file that uses an LDES feed with mapping provided is located at: [bodc_p02.vocab-config.ttl](https://github.com/vlizBE/vocabserver-deploy/blob/main/vocab-config/bodc_p02.vocab-config.ttl).

## Expected Behavior:

After loading the above configuration file, it is expected that a Docker container will start which will harvest the bodc_p02 LDES feed. Additionally, the sources should be displayed for the created vocabulary. After the LDES feed is harvested the mapping and unification should be done automatically.

## Actual Behavior:

Upon loading the configuration file, no extra Docker container starts for the LDES harvesting and no sources are displayed for the created vocabulary.

## Steps to Reproduce:

 * Load the configuration file from the provided link.
 * Observe that no extra Docker container starts.
 * Check the sources for the created vocabulary and note that none are shown.

**Comment by MikiDi** [comment]
Could you confirm this has been fixed @cedricdcc ? (make sure to pull the latest vocab-configs image)
ref: https://github.com/vlizBE/vocabserver-app/commit/7681eab2695debb6d44e17ff60f28e907d710441

**Comment by cedricdcc** [comment]
When uploading a config .ttl file the vocab-config image initiates a container that harvest an LDES feed but it initiates 2 of them at the same time.

![image](https://github.com/user-attachments/assets/56b020a2-b7ca-446d-8945-ca1a56b82379)

**Comment by MikiDi** [comment]
The config service works with intermediate processing graphs. Insertions of the same dataset in multiple graphs mislead the delta processing in the ldes-consumer-manager to think there were multiple ldes datasets inserted. See https://github.com/redpencilio/ldes-consumer-manager/commit/f43445eb4847691cf3c3c9dc6ac97452da15dbe3 for more background.
